version: '3.7'

services:
  web:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db

    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omdb
    ports:
      - 5432:5432
volumes:
  postgres_data: